[package]
name = "plume-front"
version = "0.6.1-dev"
authors = ["Plume contributors"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "=0.4.18"
stdweb-internal-runtime = "=0.1.4"
gettext = { git = "https://github.com/Plume-org/gettext/", rev = "294c54d74c699fbc66502b480a37cc66c1daa7f3" }
gettext-macros = { git = "https://github.com/Plume-org/gettext-macros/", rev = "a7c605f7edd6bfbfbfe7778026bfefd88d82db10" }
gettext-utils = { git = "https://github.com/Plume-org/gettext-macros/", rev = "a7c605f7edd6bfbfbfe7778026bfefd88d82db10" }
lazy_static = "1.3"
serde = "1.0"
serde_json = "1.0"
wasm-bindgen = "0.2.70"

[dependencies.web-sys]
version = "0.3.47"
features = [
  'Document',
  'DomTokenList',
  'Element',
  'EventTarget',
  'HtmlFormElement',
  'HtmlInputElement',
  'Navigator',
  'Node',
  'NodeList',
  'TouchEvent',
  'Window'
]
